- name: Declrae variable at play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
   - name: Accessvariable
     ansible.builtin.debug:
        msg: URL == {{URL}}

- name: Declare variable at task level
  hosts; all
  tasks:
   - name: Declare and access a variable
      ansible.builtin.debug:
       msg: URL == {{URL}}
      vars: task.example.com
            
