- name: Declrae variable at play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
   - name: Accessvariable
     ansible.builtin.debug:
        msg: URL == {{URL}}

- name: Declare in anoher file
  hosts: all
  vars_files:
   - var.ymlDeclare and access a variable
  tasks:
   - name: Access variable
     ansible.builtin.debug:
      msg: URL == {{URL}}

- name: Declare variable at task level
  hosts: all
  tasks:
   - name: Declare and access a variable
     ansible.builtin.debug:
       msg: URL == {{URL}}
     vars: 
       URL: task.examsle.com


- name: Declare variable from invenory file
  hosts: all
  connection: local
  tasks:
   - name: Access variable
     ansible.builtin.debug:
       msg: URL == {{URL}}
     vars: 
       URL: task.example.com

- name: Register a variable
  hosts: all
  connection: local
  tasks: 
    - name: Run a shell command
      ansible.builtin.shell: uptime 
      register: out
    - name: Print output
      ansible.builtin.debug:
       msg: "{{out}}"

- name: Access facts
  hosts: all
  connection: local
  tasks:
   - name: Access fact
     ansible.builtin.debug:
       msg: Ansible host name == {{ansible_fqdn}}

